"""empty message

Revision ID: 0652cec5760d
Revises: 5b42ffd710c5
Create Date: 2017-06-05 21:06:37.398984

"""

# revision identifiers, used by Alembic.
revision = '0652cec5760d'
down_revision = '5b42ffd710c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('tick', sa.SmallInteger(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'tick')
    ### end Alembic commands ###
