"""empty message

Revision ID: 1596dba0dc7f
Revises: 87daec43f7f5
Create Date: 2017-05-27 18:11:10.474132

"""

# revision identifiers, used by Alembic.
revision = '1596dba0dc7f'
down_revision = '87daec43f7f5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('recurrence_day', sa.Integer(), nullable=True),
    sa.Column('recurrence_period', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transaction', sa.Column('recurring_group_id', sa.Integer(), nullable=True))
    op.drop_column('transaction', 'recurrent_group_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('recurrent_group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('transaction', 'recurring_group_id')
    op.drop_table('recurring_group')
    ### end Alembic commands ###
