"""empty message

Revision ID: 87daec43f7f5
Revises: 53299b87b12d
Create Date: 2017-05-14 21:12:33.971017

"""

# revision identifiers, used by Alembic.
revision = '87daec43f7f5'
down_revision = '53299b87b12d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=38), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('recurrent_group_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    # ### end Alembic commands ###
